create table tb_record (id int8 generated by default as identity, count float8, description TEXT, img_url TEXT, score float8, team_name varchar(255) not null, title varchar(255) not null, primary key (id));
create table tb_score (value float8, record_id int8 not null, user_id int8 not null, primary key (record_id, user_id));
create table tb_user (id int8 generated by default as identity, email varchar(255), primary key (id));
alter table if exists tb_score add constraint FK3qyrnre06csq97y75o8rd2mav foreign key (record_id) references tb_record;
alter table if exists tb_score add constraint FKl8lgmbrjoav0thqqtqx6vrr4k foreign key (user_id) references tb_user;

INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES ('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 'Maior Torcida como Visitante em um Jogo', 6.0, 3.5, 'SPORT CLUB CORINTHIANS PAULISTA', 'Invasão ao Maracanã 1976 - 50.000 torcedores deslocados de SP para o RJ');

INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Maior Torcida do Brasil', 9.0, 3.5, 'CLUBE DE REGATAS FLAMENGO', 
 'Segundo último levantamento o flamengo conta com 42 milhões de torcedores');
 
 --------------------------------------------------------------------------------------
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 '3 Títulos em 21 dias', 4.0, 5.0, 'CLUBE DE REGATAS FLAMENGO', 
 'Em 21 dias o flamengo venceu o campeonato carioca, libertadores e mundial em dezembro de 1981');
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Campeão Brasileiro Invicto', 8.0, 3.0, 'SPORT CLUB INTERNACIONAL', 
 'Único time há vencer o campeonato brasileiro de forma INVICTA!');
 
   INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Clube Mais Antigo do Brasil', 1.0, 1.0, 'SPORT CLUBE RIO GRANDE', 
 'Clube mais antigo do Brasil');
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Vitórias Seguidas', 1.0, 1.0, 'CORITIBA FOOTBALL CLUB', 
 'CORITIBA FOOTBALL CLUB - vitórias seguidas');
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Maior Vencedor de Mundiais', 1.0, 1.0, 'SÃO PAULO FUTEBOL CLUBE', 
 'SÃO PAULO FUTEBOL CLUBE 3 x campeão');
 
      INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Maior Vencedor de Campeonato Estadual', 1.0, 1.0, 'ABC FUTEBOL CLUBE', 
 'ABC FUTEBOL CLUBE 39 x campeão');
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Clube que mais fez gols', 4.0, 4.0, 'SANTOS FUTEBOL CLUBE', 
 'SANTOS FUTEBOL CLUBE');
 
 INSERT INTO tb_record (img_url, title, count, score, team_name, description) VALUES 
('https://personal-bucket-franco.s3.sa-east-1.amazonaws.com/recorde-futebol.jpg', 
 'Maior Goleada', 4.0, 3.5, 'BOTAFOGO DE FUTEBOL E REGATAS', 
 'BOTAFOGO DE FUTEBOL E REGATAS');
 --------------------------------------------------------------------------------------
 
 INSERT INTO tb_user (email) VALUES 
('vito.cornelone@mapin.com');
 INSERT INTO tb_user (email) VALUES 
('obiwan.kenobi@mapin.com');
 INSERT INTO tb_user (email) VALUES 
('mace.windu@mapin.com');
 INSERT INTO tb_user (email) VALUES 
('tony.montana@mapin.com');
 INSERT INTO tb_user (email) VALUES 
('leia.organa@mapin.com');

-------------------------------------

 INSERT INTO tb_score (record_id, user_id, value) VALUES (1,1,4.0);
 INSERT INTO tb_score (record_id, user_id, value) VALUES (2,1,5.0);
  INSERT INTO tb_score (record_id, user_id, value) VALUES (1,4,4.0);
 INSERT INTO tb_score (record_id, user_id, value) VALUES (3,2,5.0);


