create table tb_record (id int8 generated by default as identity, count float8, description TEXT, img_url TEXT, score float8, team_name varchar(255) not null, title varchar(255) not null, primary key (id));
create table tb_score (value float8, record_id int8 not null, user_id int8 not null, primary key (record_id, user_id));
create table tb_user (id int8 generated by default as identity, email varchar(255), primary key (id));
alter table if exists tb_score add constraint FK3qyrnre06csq97y75o8rd2mav foreign key (record_id) references tb_record;
alter table if exists tb_score add constraint FKl8lgmbrjoav0thqqtqx6vrr4k foreign key (user_id) references tb_user;
